export const ORDER_RESULT_SUCCESS = 'ORDER_RESULT_SUCCESS';
// export const CONTENT_RESULT_SEARCH = 'CONTENT_RESULT_SEARCH';
// export const CONTENT_RESULT_SEARCH_FILTER = 'CONTENT_RESULT_SEARCH_FILTER';
